name: build-docker-and-publish

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: docker/build-push-action@v1.1.0
        name: Build & push Docker image on Github
        with:
          platforms: linux/amd64,linux/arm64
          tags: latest
          tag_with_ref: true
          registry: docker.pkg.github.com
          repository: brandonfl/discord-bh-38030/discord-bh-38030
          dockerfile: Dockerfile
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}